# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a4da5ec20d571b9276c605d5a4bb04f0bae913b84b7dad3accbe88f8c74e0066e1b13415e34eae054928689c897f2e1d9d22efac9050cb82f60010a3aa23776

test:
  secret_key_base: 893838a8a1837e3842f10e49dd2ff63300e6cb0b1927559f2db4484c0ca63bcfaa6ec31d437981044d9b50e5bcad7e555627b1990036d925e88ee5474d05c6e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
